### ISSUE TITLE
LV2 CVPort Plugin with latency crashes

### ISSUE THREAD

**Issue by ryukau** [falkTX/Carla#1070]
Hi.

Carla crashed when loading a plugin which has CVPort and latency.

The plugin caused crash was built with DPF. I reproduced the crash with Latency example plugin with a bit of modification. I changed `d_latency.lv2/d_latency_dsp.ttl` as following.

```ttl
    # Line 25.
    lv2:port [
        a lv2:InputPort, lv2:CVPort ; # Changed from AudioPort.
        lv2:index 0 ;
        lv2:symbol "lv2_audio_in_1" ;
        lv2:name "Audio Input 1" ;
    ] ;

    lv2:port [
        a lv2:OutputPort, lv2:CVPort ; # Changed from AudioPort.
        lv2:index 1 ;
        lv2:symbol "lv2_audio_out_1" ;
        lv2:name "Audio Output 1" ;
    ] ;
```

I'm not sure if this is caused by Carla or DPF because I only tested modified Latency plugin on Carla. I tried to load the plugin with Ardour5, but it seems like Ardour5 couldn't load CVPort plugins.

Version:
- Carla 2.0.97 (2.1-RC2), built from latest develop branch.
- Carla 2.0.96 (2.1-RC1), installed from Fedora 31 package.

Backtrace from core dump. The crash was occured on Thread 1.

```
(gdb) thread apply all bt

Thread 14 (Thread 0x7fa44f49e700 (LWP 10937)):
#0  0x00007fa465e1ca3f in poll () from /lib64/libc.so.6
#1  0x00007fa45739b86e in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#2  0x00007fa45739b9a3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#3  0x00007fa457de6825 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#4  0x00007fa457d901db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#5  0x00007fa457be0c45 in QThread::exec() () from /lib64/libQt5Core.so.5
#6  0x00007fa455657f6a in QDBusConnectionManager::run() () from /lib64/libQt5DBus.so.5
#7  0x00007fa457be1d96 in QThreadPrivate::start(void*) () from /lib64/libQt5Core.so.5
#8  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 13 (Thread 0x7fa43d28a700 (LWP 10946)):
#0  0x00007fa465df41d5 in nanosleep () from /lib64/libc.so.6
#1  0x00007fa465e1f809 in usleep () from /lib64/libc.so.6
#2  0x00007fa44eabebea in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#3  0x00007fa44ea9654d in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 12 (Thread 0x7fa44c452700 (LWP 10943)):
#0  0x00007fa4659c7d45 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fa44c4e34b2 in Jack::JackPosixProcessSync::Wait() () from /lib64/libjack.so.0
#2  0x00007fa44c4dafbd in Jack::JackMessageBuffer::Execute() () from /lib64/libjack.so.0
#3  0x00007fa44c4e2a00 in Jack::JackPosixThread::ThreadHandler(void*) () from /lib64/libjack.so.0
#4  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 11 (Thread 0x7fa43da8b700 (LWP 10945)):
#0  0x00007fa465df41d5 in nanosleep () from /lib64/libc.so.6
#1  0x00007fa465e1f809 in usleep () from /lib64/libc.so.6
#2  0x00007fa44ead4400 in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#3  0x00007fa44ea9654d in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 10 (Thread 0x7fa44e282700 (LWP 10939)):
#0  0x00007fa4659c7d45 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fa457be78b3 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () from /lib64/libQt5Core.so.5
#2  0x00007fa457be7941 in QWaitCondition::wait(QMutex*, unsigned long) () from /lib64/libQt5Core.so.5
#3  0x00007fa452d6b13d in QFileInfoGatherer::run() () from /lib64/libQt5Widgets.so.5
#4  0x00007fa457be1d96 in QThreadPrivate::start(void*) () from /lib64/libQt5Core.so.5
#5  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 9 (Thread 0x7fa44c2a3700 (LWP 10947)):
#0  0x00007fa465e221bd in syscall () from /lib64/libc.so.6
#1  0x00007fa44c4e47f2 in Jack::JackLinuxFutex::TimedWait(long) () from /lib64/libjack.so.0
#2  0x00007fa44c4caff9 in Jack::JackConnectionManager::SuspendRefNum(Jack::JackClientControl*, Jack::JackLinuxFutex*, Jack::JackClientTiming*, long) () from /lib64/libjack.so.0
#3  0x00007fa44c4c9b4f in Jack::JackClient::ExecuteThread() () from /lib64/libjack.so.0
#4  0x00007fa44c4c8db8 in Jack::JackClient::Execute() () from /lib64/libjack.so.0
#5  0x00007fa44c4e2a00 in Jack::JackPosixThread::ThreadHandler(void*) () from /lib64/libjack.so.0
#6  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#7  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 8 (Thread 0x7fa43e28c700 (LWP 10942)):
#0  0x00007fa465e279de in epoll_wait () from /lib64/libc.so.6
#1  0x00007fa44ebe6dfb in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#2  0x00007fa44ebe7a86 in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#3  0x00007fa44ebf28bc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog>::Context<ableton::link::Controller<std::function<void (unsigned long)>, std::function<void (ableton::link::Tempo)>, std::function<void (bool)>, ableton::platforms::linux::Clock<1>, ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog> >::UdpSendExceptionHandler>(ableton::link::Controller<std::function<void (unsigned long)>, std::function<void (ableton::link::Tempo)>, std::function<void (bool)>, ableton::platforms::linux::Clock<1>, ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog> >::UdpSendExceptionHandler)::{lambda(asio::io_context&, ableton::link::Controller<std::function<void (unsigned long)>, std::function<void (ableton::link::Tempo)>, std::function<void (bool)>, ableton::platforms::linux::Clock<1>, ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog> >::UdpSendExceptionHandler)#1}, std::reference_wrapper<asio::io_context>, ableton::link::Controller<std::function<void (unsigned long)>, std::function<void (ableton::link::Tempo)>, std::function<void (bool)>, ableton::platforms::linux::Clock<1>, ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog> >::UdpSendExceptionHandler> > >::_M_run() () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa4579ff3d4 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#5  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 7 (Thread 0x7fa44d503700 (LWP 10940)):
#0  0x00007fa465e279de in epoll_wait () from /lib64/libc.so.6
#1  0x00007fa44ebe6dfb in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#2  0x00007fa44ebe7a86 in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#3  0x00007fa44ebeb7d0 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog>::Context<ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog>::DefaultHandler>(ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog>::DefaultHandler)::{lambda(asio::io_context&, ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog>::DefaultHandler)#1}, std::reference_wrapper<asio::io_context>, ableton::platforms::asio::Context<ableton::platforms::posix::ScanIpIfAddrs, ableton::util::NullLog>::DefaultHandler> > >::_M_run() () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa4579ff3d4 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#5  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7fa4299a0700 (LWP 10949)):
#0  0x00007fa465df41d5 in nanosleep () from /lib64/libc.so.6
#1  0x00007fa465e1f809 in usleep () from /lib64/libc.so.6
#2  0x00007fa44ea9735a in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#3  0x00007fa44ea9654d in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7fa44fc9f700 (LWP 10936)):
#0  0x00007fa465e1ca3f in poll () from /lib64/libc.so.6
#1  0x00007fa45486938a in _xcb_conn_wait () from /lib64/libxcb.so.1
#2  0x00007fa45486afea in xcb_wait_for_event () from /lib64/libxcb.so.1
#3  0x00007fa44fdc7d48 in QXcbEventQueue::run() () from /lib64/libQt5XcbQpa.so.5
#4  0x00007fa457be1d96 in QThreadPrivate::start(void*) () from /lib64/libQt5Core.so.5
#5  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7fa44c3d1700 (LWP 10944)):
#0  0x00007fa465e1841c in read () from /lib64/libc.so.6
#1  0x00007fa44c4e3c42 in Jack::JackClientSocket::Read(void*, int) () from /lib64/libjack.so.0
#2  0x00007fa44c4e707d in Jack::JackSocketClientChannel::Execute() () from /lib64/libjack.so.0
#3  0x00007fa44c4e2a00 in Jack::JackPosixThread::ThreadHandler(void*) () from /lib64/libjack.so.0
#4  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7fa43ca89700 (LWP 10948)):
#0  0x00007fa465df41d5 in nanosleep () from /lib64/libc.so.6
#1  0x00007fa465e1f809 in usleep () from /lib64/libc.so.6
#2  0x00007fa44eae7272 in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#3  0x00007fa44ea9654d in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fa44cd02700 (LWP 10941)):
#0  0x00007fa4659c807a in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fa44ebe55cc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<ableton::platforms::LockFreeCallbackDispatcher<std::function<void ()>, std::chrono::duration<long, std::ratio<1l, 1000l> > >::LockFreeCallbackDispatcher(std::function<void ()>, std::chrono::duration<long, std::ratio<1l, 1000l> >)::{lambda()#1}> > >::_M_run() () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#2  0x00007fa4579ff3d4 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#3  0x00007fa4659c14e2 in start_thread () from /lib64/libpthread.so.0
#4  0x00007fa465e276a3 in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fa4658656c0 (LWP 10934)):
#0  0x00007fa465e8aa35 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007fa44c21667d in ?? () from /home/cu/.lv2/d_latency.lv2/d_latency_dsp.so
#2  0x00007fa44c2198bd in ?? () from /home/cu/.lv2/d_latency.lv2/d_latency_dsp.so
#3  0x00007fa44eb3b9bd in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#4  0x00007fa44eb3cfd0 in ?? () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#5  0x00007fa44eaafefd in CarlaBackend::CarlaEngine::addPlugin(CarlaBackend::BinaryType, CarlaBackend::PluginType, char const*, char const*, char const*, long, void const*, unsigned int) () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#6  0x00007fa44ea9c105 in carla_add_plugin () from /home/cu/code/cpp/temp/Carla/bin/libcarla_standalone2.so
#7  0x00007fa450daeaa8 in ffi_call_unix64 () from /lib64/libffi.so.6
#8  0x00007fa450dae2a4 in ffi_call () from /lib64/libffi.so.6
#9  0x00007fa450c8f8fa in _ctypes_callproc () from /usr/lib64/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so
#10 0x00007fa450c9008c in PyCFuncPtr_call () from /usr/lib64/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so
#11 0x00007fa465b18c6c in _PyObject_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#12 0x00007fa465b1a279 in call_function () from /lib64/libpython3.7m.so.1.0
#13 0x00007fa465b54e2d in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#14 0x00007fa465b082d2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#15 0x00007fa465b1a0ef in call_function () from /lib64/libpython3.7m.so.1.0
#16 0x00007fa465b54e2d in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#17 0x00007fa465b0893a in _PyFunction_FastCallDict () from /lib64/libpython3.7m.so.1.0
#18 0x00007fa465add8c6 in _PyObject_Call_Prepend () from /lib64/libpython3.7m.so.1.0
#19 0x00007fa465b0904e in PyObject_Call () from /lib64/libpython3.7m.so.1.0
#20 0x00007fa458360590 in PyQtSlot::call(_object*, _object*) const () from /usr/lib64/python3.7/site-packages/PyQt5/QtCore.so
#21 0x00007fa458360a38 in PyQtSlot::invoke(void**, _object*, void*, bool) const () from /usr/lib64/python3.7/site-packages/PyQt5/QtCore.so
#22 0x00007fa458360bf0 in PyQtSlot::invoke(void**, _object*, void*) const () from /usr/lib64/python3.7/site-packages/PyQt5/QtCore.so
#23 0x00007fa45836353d in qt_metacall_worker(_sipSimpleWrapper*, _typeobject*, _sipTypeDef*, QMetaObject::Call, int, void**) () from /usr/lib64/python3.7/site-packages/PyQt5/QtCore.so
#24 0x00007fa458363635 in qpycore_qobject_qt_metacall(_sipSimpleWrapper*, _sipTypeDef*, QMetaObject::Call, int, void**) () from /usr/lib64/python3.7/site-packages/PyQt5/QtCore.so
#25 0x00007fa457dbb9dc in QMetaObject::activate(QObject*, int, int, void**) () from /lib64/libQt5Core.so.5
#26 0x00007fa452b31456 in QAction::triggered(bool) () from /lib64/libQt5Widgets.so.5
#27 0x00007fa452b33b92 in QAction::activate(QAction::ActionEvent) () from /lib64/libQt5Widgets.so.5
#28 0x00007fa452c300b0 in QAbstractButtonPrivate::click() () from /lib64/libQt5Widgets.so.5
#29 0x00007fa452c302d5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /lib64/libQt5Widgets.so.5
#30 0x00007fa452d2454e in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /lib64/libQt5Widgets.so.5
#31 0x00007fa452b7ac7e in QWidget::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#32 0x00007fa452d245f8 in QToolButton::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#33 0x00007fa452b37ab6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#34 0x00007fa452b413a3 in QApplication::notify(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#35 0x00007fa4531ef586 in sipQApplication::notify(QObject*, QEvent*) () from /usr/lib64/python3.7/site-packages/PyQt5/QtWidgets.so
#36 0x00007fa457d913e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#37 0x00007fa452b404b7 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib64/libQt5Widgets.so.5
#38 0x00007fa452b96c8d in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /lib64/libQt5Widgets.so.5
#39 0x00007fa452b99c8c in QWidgetWindow::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#40 0x00007fa452b37ab6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#41 0x00007fa452b41150 in QApplication::notify(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#42 0x00007fa4531ef586 in sipQApplication::notify(QObject*, QEvent*) () from /usr/lib64/python3.7/site-packages/PyQt5/QtWidgets.so
#43 0x00007fa457d913e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#44 0x00007fa454e7fb83 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib64/libQt5Gui.so.5
#45 0x00007fa454e8137b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib64/libQt5Gui.so.5
#46 0x00007fa454e5d6eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Gui.so.5
#47 0x00007fa44fdc8d5e in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /lib64/libQt5XcbQpa.so.5
#48 0x00007fa45739b570 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#49 0x00007fa45739b900 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#50 0x00007fa45739b9a3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#51 0x00007fa457de6825 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#52 0x00007fa457d901db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#53 0x00007fa457d980b6 in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#54 0x00007fa4531edfc1 in meth_QApplication_exec_ () from /usr/lib64/python3.7/site-packages/PyQt5/QtWidgets.so
#55 0x00007fa465ae7c0e in _PyMethodDef_RawFastCallKeywords () from /lib64/libpython3.7m.so.1.0
#56 0x00007fa465ae7d43 in _PyCFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#57 0x00007fa465b1a203 in call_function () from /lib64/libpython3.7m.so.1.0
#58 0x00007fa465b54e2d in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#59 0x00007fa465b082d2 in _PyFunction_FastCallKeywords () from /lib64/libpython3.7m.so.1.0
#60 0x00007fa465b1a0ef in call_function () from /lib64/libpython3.7m.so.1.0
#61 0x00007fa465b50576 in _PyEval_EvalFrameDefault () from /lib64/libpython3.7m.so.1.0
#62 0x00007fa465b07430 in _PyEval_EvalCodeWithName () from /lib64/libpython3.7m.so.1.0
#63 0x00007fa465b081c9 in PyEval_EvalCodeEx () from /lib64/libpython3.7m.so.1.0
#64 0x00007fa465b980db in PyEval_EvalCode () from /lib64/libpython3.7m.so.1.0
#65 0x00007fa465bd9c43 in run_mod () from /lib64/libpython3.7m.so.1.0
#66 0x00007fa465bda197 in PyRun_FileExFlags () from /lib64/libpython3.7m.so.1.0
#67 0x00007fa465be068a in PyRun_SimpleFileExFlags () from /lib64/libpython3.7m.so.1.0
#68 0x00007fa465be2411 in pymain_main () from /lib64/libpython3.7m.so.1.0
#69 0x00007fa465be25bc in _Py_UnixMain () from /lib64/libpython3.7m.so.1.0
#70 0x00007fa465d4d1a3 in __libc_start_main () from /lib64/libc.so.6
#71 0x00005584ef24c08e in _start ()
```

**Comment by falkTX** [comment]
nice find, just before release. let me try to fix this now..

**Comment by ryukau** [comment]
It's working now. Thanks for the fix!
