### ISSUE TITLE
Carla patchbay/rack plugin freezes ardour if removed right after its GUI is closed

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#1109]
Reproduction steps:

1. Open Ardour
2. Create a new midi track and add carla-patchbay or carla-rack, (lv2 or lxvst version) plugin to it.
3. Wait for the GUI to open
4. Close the GUI and right click on the plugin and choose remove as fast as you can
5. Observe Ardour freezing undefinitly

**Comment by terencode** [comment]
Sometimes I see this after closing the GUI fast: 
```
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla_host.py", line 94, in flush
    def flush(self):
  File "/usr/share/carla/resources/carla_shared.py", line 740, in signalHandler
    gCarla.gui.SIGTERM.emit()
RuntimeError: wrapped C/C++ object of type CarlaMiniW has been deleted
```

**Comment by terencode** [comment]
I can still reproduce on latest `develop` 0bd8c8175.

**Comment by falkTX** [comment]
FYI I am not able to reproduce this with carla 2.2 and ardour 6.
