### ISSUE TITLE
No ALSA in Engine Core.

### ISSUE THREAD

**Issue by KottV** [falkTX/Carla#1115]
Hi,

Maybe I overlooked something, but with 2.1 there is now ALSA option in driver selectons, just JACK, JACK (RtAudio) and PulseAudio. I use ALSA-only setup often, and this is valuable miss.

**Comment by KottV** [comment]
I've read https://kx.studio/News/?action=view&url=carla-21-rc1-is-here announce and didn't find any mention about this.
I'm building Carla from sources, and make features says:
---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES

Sadly, binary from https://github.com/falkTX/Carla/releases/download/v2.1/Carla_2.1-linux64.tar.xz doesn't run:

```
./Carla
Carla self-contained executable 2.0.97 (2.1-RC2), based on UnZipSFX.
Launching: '/tmp/carla-2.1/carla'
Traceback (most recent call last):
  File "./lib/__startup__.py", line 40, in run
  File "./lib/Console.py", line 23, in run
  File "source/frontend/carla", line 22, in <module>
  File "./lib/carla_host.py", line 30, in <module>
ImportError: /usr/lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /tmp/carla-2.1/lib/PyQt5/QtCore.so)
```

I'm on openSUSE TW with Qt5-5.14.1
