### ISSUE TITLE
Carla VST is not loading GUI

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#1170]
Latest version carla-git 5:2:1+git20200607

Getting a black screen in Waveform 10.4.7
Does not load GUI in Reaper 6.11 or Bitwig 3.2.1

Black Screen in JUCE6 AudioPluginHost

with this error...

```
Opening VST UI: CarlaRackFX
Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin"
Carla 2.2.0-beta1 started, status:
  Python version: 3.7.3
  Qt version:     5.11.3
  PyQt version:   5.11.3
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
Traceback (most recent call last):
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 609, in <module>
    gui = CarlaEmbedW(host, winId, isPatchbay)
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 474, in __init__
    self.addLine()
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 505, in addLine
    line = QFrame(self)
NameError: name 'QFrame' is not defined
CarlaPipeCommon::_writeMsgBuffer(..., 13) - failed with -1 (true), message was:
runtime-info
Carla assertion failure: "fUiServer.writeAndFixMessage("runtime-info")" in file CarlaEngineNative.cpp, line 1412

```

**Comment by falkTX** [comment]
My bad, will fix right away

**Comment by tank-trax** [comment]
when will this be applied? 
not seeing an upgrades available for Carla yet, thanks

**Comment by tank-trax** [comment]
just saw the update for carla-git, thanks

**Comment by tank-trax** [comment]
I am getting this error. Should I open another issue?

`Carla assertion failure: "obj->plugin == nullptr" in file carla-vst.cpp, line 973`

**Comment by falkTX** [comment]
that is expected, depending on the host.
ignore that for now
