### ISSUE TITLE
segmentation fault on start for JACK with ALSA-MIDI

### ISSUE THREAD

**Issue by wvengen** [falkTX/Carla#1185]
When running Carla with audio driver _JACK with ALSA-MIDI_ with JACK running on [ffado](http://ffado.org/) connected to an [AudioFire Pre8](https://www.soundonsound.com/reviews/echo-audiofire-pre-8) device, it crashes right after audio init. This does not happen with the _JACK_ audio driver. Neither does it happen when I run JACK on my internal MacbookPro11,1 soundcard.

```
CarlaEngineRtAudio::init("Carla")
Segmentation fault (core dumped)
```

**Comment by wvengen** [comment]
Running with strace (Carla without debug, this time) shows this at the end:
```
ind(25, {sa_family=AF_UNIX, sun_path="/dev/shm/jack_Carla_1000_0"}, 110) = 0
listen(25, 100)                         = 0
mmap(NULL, 528384, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fdfa81a5000
mprotect(0x7fdfa81a6000, 524288, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fdfa8224fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tid=[73638], tls=0x7fdfa8225700, child_tidptr=0x7fdfa82259d0) = 73638
getpid()                                = 73625
write(24, "\27\0\0\0", 4)               = 4
write(24, "I\0\0\0", 4)                 = 4
write(24, "\231\37\1\0", 4)             = 4
write(24, "\377\377\377\377", 4)        = 4
write(24, "Carla\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 65) = 65
read(24, "\0\0\0\0", 4)                 = 4
read(24, "\1\0\0\0", 4)                 = 4
read(24, "\6\0\0\0", 4)                 = 4
read(24, "\0\0\0\0", 4)                 = 4
getuid()                                = 1000
semget(0x282929, 0, 000)                = 2
semtimedop(2, [{0, -1, SEM_UNDO}], 1, NULL) = 0
openat(AT_FDCWD, "/dev/shm/jack-shm-registry", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 33
mmap(NULL, 70744, PROT_READ|PROT_WRITE, MAP_SHARED, 33, 0) = 0x7fdfa8193000
close(33)                               = 0
semtimedop(2, [{0, 1, SEM_UNDO}], 1, NULL) = 0
openat(AT_FDCWD, "/dev/shm/jack-1000-1", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 33
mmap(NULL, 1187, PROT_READ|PROT_WRITE, MAP_SHARED, 33, 0) = 0x7fdfa98f7000
close(33)                               = 0
mlock(0x7fdfa98f7000, 1187)             = 0
openat(AT_FDCWD, "/dev/shm/jack-1000-0", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 33
mmap(NULL, 82280346, PROT_READ|PROT_WRITE, MAP_SHARED, 33, 0) = 0x7fdf7b188000
close(33)                               = 0
mlock(0x7fdf7b188000, 82280346)         = 0
openat(AT_FDCWD, "/dev/shm/jack-1000-6", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 33
mmap(NULL, 422, PROT_READ|PROT_WRITE, MAP_SHARED, 33, 0) = 0x7fdfa98f6000
close(33)                               = 0
mlock(0x7fdfa98f6000, 422)              = 0
unlink("/dev/shm/jack-1000-6")          = 0
getpid()                                = 73625
getuid()                                = 1000
openat(AT_FDCWD, "/dev/shm/jack_sem.1000_default_Carla", O_RDWR|O_NOFOLLOW|O_CLOEXEC) = 33
mmap(NULL, 12, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_LOCKED, 33, 0) = 0x7fdfa98f5000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
```

**Comment by wvengen** [comment]
I'm not really sure how to debug this, since Carla is a Python program, but I could run Carla, suspend it, attach gdb, continue.

And from then on, I can't seem to reproduce the issue.
Closing for now, sorry for the noise.

**Comment by wvengen** [comment]
Ok, after restarting JACK I can reproduce the issue, but trying to debug seems to mess up something. Suspending Carla, attaching gdb, continuing after SIGSTP seems to keep Carla stuck.

**Comment by falkTX** [comment]
when you install carla you can use `carla --gdb`, or if running locally `gdb --args python3 source/frontend/carla`

**Comment by wvengen** [comment]
Ah, thanks :) Using `carla --gdb` doesn't seem to make a difference, it segfaults.
Running gdb directly _does_ work.
```
CarlaEngineRtAudio::init("Carla")
No device set, using 2 inputs and 2 outputs
[New Thread 0x7fffe8203700 (LWP 55481)]
[New Thread 0x7fffe8182700 (LWP 55482)]

Thread 1 "carla" received signal SIGSEGV, Segmentation fault.
0x00007fffeb36ef05 in RtApiJack::probeDeviceOpen (this=0x100a8c0, device=0, mode=RtApi::OUTPUT, channels=2, firstChannel=0, format=16, bufferSize=0x7fffffffc5bc, 
    options=0x7fffffffc5f0) at RtAudio.cpp:2084
2084	  if ( ports[ firstChannel ] ) {
(gdb) bt
#0  0x00007fffeb36ef05 in RtApiJack::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) (this=0x100a8c0, device=0, mode=RtApi::OUTPUT, channels=2, firstChannel=0, format=16, bufferSize=0x7fffffffc5bc, options=0x7fffffffc5f0) at RtAudio.cpp:2084
#1  0x00007fffeb36e471 in RtApi::openStream(RtAudio::StreamParameters*, RtAudio::StreamParameters*, unsigned long, unsigned int, unsigned int*, int (*)(void*, void*, unsigned int, double, unsigned int, void*), void*, RtAudio::StreamOptions*, bool (*)(unsigned int, void*), void (*)(RtAudioError::Type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))
    (this=0x100a8c0, oParams=0x7fffffffc5e4, iParams=0x7fffffffc5d8, format=16, sampleRate=44100, bufferFrames=0x7fffffffc5bc, callback=0x7fffeacef351 <CarlaBackend::CarlaEngineRtAudio::carla_rtaudio_process_callback(void*, void*, unsigned int, double, unsigned int, void*)>, userData=0x15e7a60, options=0x7fffffffc5f0, bufSizeCallback=0x7fffeacef39f <CarlaBackend::CarlaEngineRtAudio::carla_rtaudio_buffer_size_callback(unsigned int, void*)>, errorCallback=0x0) at RtAudio.cpp:324
#2  0x00007fffeb36e057 in RtAudio::openStream(RtAudio::StreamParameters*, RtAudio::StreamParameters*, unsigned long, unsigned int, unsigned int*, int (*)(void*, void*, unsigned int, double, unsigned int, void*), void*, RtAudio::StreamOptions*, bool (*)(unsigned int, void*), void (*)(RtAudioError::Type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))
    (this=0x15e7a70, outputParameters=0x7fffffffc5e4, inputParameters=0x7fffffffc5d8, format=16, sampleRate=44100, bufferFrames=0x7fffffffc5bc, callback=0x7fffeacef351 <CarlaBackend::CarlaEngineRtAudio::carla_rtaudio_process_callback(void*, void*, unsigned int, double, unsigned int, void*)>, userData=0x15e7a60, options=0x7fffffffc5f0, bufSizeCallback=0x7fffeacef39f <CarlaBackend::CarlaEngineRtAudio::carla_rtaudio_buffer_size_callback(unsigned int, void*)>, errorCallback=0x0) at RtAudio.cpp:228
#3  0x00007fffeacecac4 in CarlaBackend::CarlaEngineRtAudio::init(char const*) (this=0x15e7a60, clientName=0x7fffe906a920 "Carla") at CarlaEngineRtAudio.cpp:306
#4  0x00007fffeac7cfff in carla_engine_init(CarlaHostHandle, char const*, char const*)
    (handle=0x7fffeb7094a0 <carla_standalone_host_init::gStandalone>, driverName=0x7fffe90678d0 "JACK with ALSA-MIDI", clientName=0x7fffe906a920 "Carla")
    at CarlaStandalone.cpp:355
#5  0x00007ffff7faaff5 in  () at /usr/lib/x86_64-linux-gnu/libffi.so.7
#6  0x00007ffff7faa40a in  () at /usr/lib/x86_64-linux-gnu/libffi.so.7
#7  0x00007ffff739069c in _ctypes_callproc () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#8  0x00007ffff7390c9c in  () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#9  0x00000000005f2246 in _PyObject_MakeTpCall ()
#10 0x000000000056c70f in _PyEval_EvalFrameDefault ()
#11 0x0000000000507d1e in  ()
#12 0x000000000056c056 in _PyEval_EvalFrameDefault ()
#13 0x00000000005f19cb in _PyFunction_Vectorcall ()
#14 0x0000000000507e1c in  ()
#15 0x00000000005f0e3e in PyObject_Call ()
#16 0x00007ffff724e070 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#17 0x00007ffff724e518 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#18 0x00007ffff724e6d0 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#19 0x00007ffff725101d in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#20 0x00007ffff7251115 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-38-x86_64-linux-gnu.so
#21 0x00007ffff6d71d5a in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fffed7cb25d in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fffed8e0148 in QMainWindow::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fffedf2c19b in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#25 0x00007fffed788a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fffed7920f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fffee08fbf6 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#28 0x00007ffff6d4593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6d485b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff6d9df67 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007fffed788a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fffed7920f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fffee08fbf6 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#28 0x00007ffff6d4593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6d485b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff6d9df67 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--C
#31 0x00007ffff6288fbd in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff6289240 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff62892e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff6d9d565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff6d444db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff6d4c246 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007fffee0509c1 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#38 0x00000000005f16ca in PyCFunction_Call ()
#39 0x00000000005f2246 in _PyObject_MakeTpCall ()
#40 0x000000000056c70f in _PyEval_EvalFrameDefault ()
#41 0x00000000005f19cb in _PyFunction_Vectorcall ()
#42 0x0000000000567325 in _PyEval_EvalFrameDefault ()
#43 0x00000000005654d2 in _PyEval_EvalCodeWithName ()
#44 0x0000000000686d53 in PyEval_EvalCode ()
#45 0x0000000000676101 in  ()
#46 0x000000000067617f in  ()
#47 0x0000000000676237 in PyRun_FileExFlags ()
#48 0x00000000006782ba in PyRun_SimpleFileExFlags ()
#49 0x00000000006af5ce in Py_RunMain ()
#50 0x00000000006af959 in Py_BytesMain ()
#51 0x00007ffff7dcf0b3 in __libc_start_main (main=
    0x4ec640 <main>, argc=2, argv=0x7fffffffded8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdec8) at ../csu/libc-start.c:308
#52 0x00000000005f69be in _start ()
(gdb) print ports
$1 = (const char **) 0x0
(gdb) print firstChannel
$2 = 0
(gdb) print stream_
$3 = {device = {11111, 11111}, apiHandle = 0x0, mode = RtApi::UNINITIALIZED, state = RtApi::STREAM_CLOSED, userBuffer = {0x0, 0x0}, deviceBuffer = 0x0, doConvertBuffer = {false, 
    false}, userInterleaved = true, deviceInterleaved = {true, true}, doByteSwap = {false, false}, sampleRate = 44100, bufferSize = 0, nBuffers = 0, nUserChannels = {0, 0}, 
  nDeviceChannels = {0, 0}, channelOffset = {0, 0}, latency = {0, 0}, userFormat = 0, deviceFormat = {0, 0}, mutex = pthread_mutex_t = {Type = Normal, Status = Not acquired, 
    Robust = No, Shared = No, Protocol = None}, callbackInfo = {object = 0x0, thread = 8319607701868147574, callback = 0x0, userData = 0x0, bufSizeCallback = 0x0, 
    errorCallback = 0x0, apiInfo = 0x0, isRunning = false, doRealtime = false, priority = 0}, convertInfo = {{channels = 0, inJump = 0, outJump = 0, inFormat = 0, outFormat = 0, 
      inOffset = std::vector of length 0, capacity 0, outOffset = std::vector of length 0, capacity 0}, {channels = 0, inJump = 0, outJump = 0, inFormat = 0, outFormat = 0, 
      inOffset = std::vector of length 0, capacity 0, outOffset = std::vector of length 0, capacity 0}}, streamTime = 0, lastTickTimestamp = {tv_sec = 3707715344671074668, 
    tv_usec = 140737136036362}}
```

The soundcard used here has a JACK MIDI port (and the internal soundcard not), if that makes a difference.

**Comment by falkTX** [comment]
well it makes a difference maybe, as this backtrace is quite useful

**Comment by falkTX** [comment]
please try with 0df641fe9fb76d0fa31a63b66999e047e0ce00c9

**Comment by wvengen** [comment]
Wow, that's fast ... and no crash anymore! :) :tada: 
(I'm seeing no ports at all in the patchbay, but that will be another issue.)
