### ISSUE TITLE
Segfault on right-click in VST3 GUI

### ISSUE THREAD

**Issue by cbix** [falkTX/Carla#1292]
As discussed in [this issue](https://github.com/antanasbruzas/abNinjam/issues/6#issuecomment-723555370) in abNinjam, this might be a bug in either Carla 2.2.0 or the included VST3 lib:

```
Thread 1 "carla" received signal SIGSEGV, Segmentation fault.
0x00007fffbdad4608 in VSTGUI::VST3Editor::onMouseDown(VSTGUI::CFrame*, VSTGUI::CPoint const&, VSTGUI::CButtonState const&) ()
   from /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
(gdb) thread apply all bt
...
Thread 1 (Thread 0x7ffff78b8740 (LWP 81543) "carla"):
#0  0x00007fffbdad4608 in VSTGUI::VST3Editor::onMouseDown(VSTGUI::CFrame*, VSTGUI::CPoint const&, VSTGUI::CButtonState const&) () at /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
#1  0x00007fffbda3e0b5 in VSTGUI::CFrame::callMouseObserverMouseDown(VSTGUI::CPoint const&, VSTGUI::CButtonState const&) () at /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
#2  0x00007fffbda3e2f5 in VSTGUI::CFrame::onMouseDown(VSTGUI::CPoint&, VSTGUI::CButtonState const&) () at /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
#3  0x00007fffbda3e65f in non-virtual thunk to VSTGUI::CFrame::platformOnMouseDown(VSTGUI::CPoint&, VSTGUI::CButtonState const&) () at /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
#4  0x00007fffbdac6595 in VSTGUI::X11::Frame::Impl::onEvent(xcb_button_press_event_t&) () at /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
#5  0x00007fffbdac9418 in VSTGUI::X11::RunLoop::Impl::onEvent() () at /home/florian/.vst3/abNinjam.vst3/Contents/x86_64-linux/abNinjam.so
#6  0x00007fffe918bbb3 in  () at /usr/lib/carla/libcarla_standalone2.so
...
```

How to reproduce:

1. build and install the latest version of [abNinjam](https://github.com/antanasbruzas/abNinjam). The GUI only is only available in the VST3 build.
2. start Carla 2.2.0 `carla --gdb` and load the abNinjam VST3 plugin
3. open the plugin GUI and right-click on the logo

**Comment by federicobriata** [comment]
I'm also getting this segfault here with carla, even when i want to remove the plugin. The same with lv2.
I'm not fully sure it's Carla issue...
@falkTX

**Comment by cbix** [comment]
This came up again when testing [uhhyou-plugins](https://github.com/ryukau/VSTPlugins):
```
#0  0x00007fff9e8f300b in VSTGUI::BarBox<SomeDSP::LinearScale<double> >::onMouseDownEvent(VSTGUI::MouseDownEvent&) () at /usr/lib/vst3/L4Reverb.vst3/Contents/x86_64-linux/L4Reverb.so
#1  0x00007fff9e961c70 in VSTGUI::CViewContainer::onMouseDownEvent(VSTGUI::MouseDownEvent&) () at /usr/lib/vst3/L4Reverb.vst3/Contents/x86_64-linux/L4Reverb.so
#2  0x00007fff9e941fa4 in VSTGUI::CFrame::dispatchMouseDownEvent(VSTGUI::MouseDownEvent&) () at /usr/lib/vst3/L4Reverb.vst3/Contents/x86_64-linux/L4Reverb.so
#3  0x00007fff9e9429ec in VSTGUI::CFrame::dispatchEvent(VSTGUI::Event&) () at /usr/lib/vst3/L4Reverb.vst3/Contents/x86_64-linux/L4Reverb.so
#4  0x00007fff9e97e128 in VSTGUI::X11::Frame::Impl::onEvent(xcb_button_press_event_t&) () at /usr/lib/vst3/L4Reverb.vst3/Contents/x86_64-linux/L4Reverb.so
#5  0x00007fff9e980a1b in VSTGUI::X11::RunLoop::Impl::onEvent() () at /usr/lib/vst3/L4Reverb.vst3/Contents/x86_64-linux/L4Reverb.so
```

This is not reproducible in Reaper or Ardour.
