### ISSUE TITLE
zynaddsubfx internal plugin GUI can crash on close

### ISSUE THREAD

**Issue by laanwj** [falkTX/Carla#132]
Output:

```
Trying to get window...
Match found using UTF-8 name
Match found using simple name

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd0dbe700 (LWP 2969)]
0x00007fffbfa835ea in PresetsUI::~PresetsUI (this=0x7fff8006fac0, __in_chrg=<optimized out>) at zynaddsubfx/UI/PresetsUI.cpp:129
129       copywin->hide();delete(copywin);
(gdb) bt
#0  0x00007fffbfa835ea in PresetsUI::~PresetsUI (this=0x7fff8006fac0, __in_chrg=<optimized out>) at zynaddsubfx/UI/PresetsUI.cpp:129
#1  0x00007fffbfa8371e in MasterUI::~MasterUI (this=0x7fff80000f60, __in_chrg=<optimized out>) at zynaddsubfx/UI/MasterUI.cpp:2398
#2  0x00007fffbf9f8645 in ZynAddSubFxThread::run (this=0x3e243c8) at zynaddsubfx-synth.cpp:474
#3  0x00007fffbf8cd6ab in _runEntryPoint (this=0x3e243c8) at ../../utils/CarlaThread.hpp:266
#4  CarlaThread::_entryPoint (userData=0x3e243c8) at ../../utils/CarlaThread.hpp:278
#5  0x00007ffff7bc4182 in start_thread (arg=0x7fffd0dbe700) at pthread_create.c:312
#6  0x00007ffff78f0fbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

But also

```
Match found using UTF-8 name
Match found using simple name
Trying to get window...
Match found using UTF-8 name
Match found using simple name

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb0cc2700 (LWP 3030)]
0x00007fffbedc2255 in Fl_Widget::contains (this=this@entry=0x7fff9c632ed0, o=0xd00000000, o@entry=0x7fff9c2a2880) at ../src/Fl_Widget.cxx:263
263       for (; o; o = o->parent_) if (o == this) return 1;
(gdb) bt
#0  0x00007fffbedc2255 in Fl_Widget::contains (this=this@entry=0x7fff9c632ed0, o=0xd00000000, o@entry=0x7fff9c2a2880) at ../src/Fl_Widget.cxx:263
#1  0x00007fffbed875a9 in Fl_Group::clear (this=this@entry=0x7fff9c632ed0) at ../src/Fl_Group.cxx:397
#2  0x00007fffbed876cc in Fl_Group::~Fl_Group (this=0x7fff9c632ed0, __in_chrg=<optimized out>) at ../src/Fl_Group.cxx:452
#3  0x00007fffbed876f9 in Fl_Group::~Fl_Group (this=0x7fff9c632ed0, __in_chrg=<optimized out>) at ../src/Fl_Group.cxx:453
#4  0x00007fffbed87684 in Fl_Group::clear (this=this@entry=0x7fff9c2a2880) at ../src/Fl_Group.cxx:427
#5  0x00007fffbed876cc in Fl_Group::~Fl_Group (this=0x7fff9c2a2880, __in_chrg=<optimized out>) at ../src/Fl_Group.cxx:452
#6  0x00007fffbf9f8645 in ZynAddSubFxThread::run (this=0x24f4508) at zynaddsubfx-synth.cpp:474
#7  0x00007fffbf8cd6ab in _runEntryPoint (this=0x24f4508) at ../../utils/CarlaThread.hpp:266
#8  CarlaThread::_entryPoint (userData=0x24f4508) at ../../utils/CarlaThread.hpp:278
#9  0x00007ffff7bc4182 in start_thread (arg=0x7fffb0cc2700) at pthread_create.c:312
#10 0x00007ffff78f0fbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

I cannot reliably reproduce it, but it happens regularly, especially when two or more instances of the plugin GUI are open and I close one, or both, in random order. But it also happened to me when only running one instance.
- Version: HEAD 63255d2, compiled using DEFAULT_QT = 5
- ntk build from source latest git (9884cca)

**Comment by falkTX** [comment]
why do you close this?

**Comment by laanwj** [comment]
I closed all my old issues! Happy to reopen if it's still relevant.

**Comment by falkTX** [comment]
Maybe not, dont know yet. It has been a while since I updated the carla internal plugins, so it is very likely this has been fixed in official zynaddsubfx now
