### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by xnghu** [falkTX/Carla#1510]
Description of how I can reproduce my bug:

0. Running Debian Sid. Freshly updated and upgraded as of moments before posting this.
1. Add the KXStudio repositories via kxstudio-repos.deb via https://kx.studio/Repositories
2. Update and install Carla with `sudo apt-get install carla`  (Successfull)
3. Running Carla gives: 
```
$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 40, in <module>
    from PyQt5.QtCore import (ModuleNotFoundError: No module named 'PyQt5'`
```
4. Attempting to manually install python3-pyqt5 shows it's already installed:
```
$ sudo apt-get install python3-pyqt5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pyqt5 is already the newest version (5.15.6+dfsg-1).
```
Expected behavior: 
Carla installs and works without further dependency management when using the package manager and the KX Repos.

Please let me know what other info I might provide to help solve this

**Comment by falkTX** [comment]
This is a debian problem, not Carla.
If you have python3-pyqt5 installed then this simple command should run without errors:
```
python3 -c "import PyQt5"
```

**Comment by edward3h** [comment]
I ran into the same issue on Ubuntu 21.10.

The workaround was to install PyQt5 with pip:
`pip install PyQt5`

**Comment by falkTX** [comment]
I seriously advise against that.
installing pyqt through pip is likely to break many things

**Comment by edward3h** [comment]
Do you have a better suggestion?

**Comment by falkTX** [comment]
It is something to see in your own distro. installing python3-pyqt5 should not be hard, and if they broke it they really need to fix it then

**Comment by Schneckensuppe** [comment]
hi,
I'm on Debian GNU/Linux 11 (bullseye), with gnome.
I had the same problem, which I solved by launching "python3", you can see its default python version, for me "python3.8.9"
then installing via pip pyqt5:
"python3.8 -m pip install pyqt5"

**Comment by mxmilkiib** [comment]
For a more robust system, installing it via the package manager rather than pip is advised. The package manager knows nothing about what pip does, so when the package manager (and I've no idea how it didn't install it as a dependency previously) eventually tries to install the module, there will either be an error or two copies of the module on the system that could eventually go out of sync with other things and cause a problem.

**Comment by tresf** [comment]
Seeing this same issue on Manjaro just testing out the library.

```bash
sudo pacman -S carla
```

```bash
carla
# Traceback (most recent call last):
#   File "/usr/share/carla/carla", line 22, in <module>
#     from carla_host import *
#   File "/usr/share/carla/carla_host.py", line 40, in <module>
#     from PyQt5.QtCore import (
# ModuleNotFoundError: No module named 'PyQt5'
```

```bash
python --version
# 3.12.7
```

```bash
python3 -c "import PyQt5"
# Traceback (most recent call last):
#  File "<string>", line 1, in <module>
# ModuleNotFoundError: No module named 'PyQt5'
```

I know it's a packaging problem with the OS and not this project, but wanted to share.

**Comment by Xlaits** [comment]
I'm getting the same issues in Arch, using both the main and aur git versions
```
[xlaits@SidheBox ~]$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 40, in <module>
    from PyQt5.QtCore import (
ModuleNotFoundError: No module named 'PyQt5'
```
I can confirm I have both PyQt5 and python-PyQt5 installed.

**Comment by cibban** [comment]
Still broken in Ubuntu 25.04 both with the standard repos, the KX Studio repos and the git-version from the latter. Installing python3-pyqt5 from the package manager did nothing but the pip method did the trick. It may not be as robust as installing via the package manager but at least it works.

This is obviously not a bug in Carla, so this is just for info and to hopefully help others in the same situation, at least for the time being, but what project should I report this to? It doesn't seem to be distro specific but since using pip works, it can't be Python either. Or can it? Python is not my forté, I have to admit.

**Comment by xkr47** [comment]
For me, the reason for carla not working was:

I had installed another unrelated python package X using `pip` to a standalone directory that I created using the `python3 -m venv X` convention, and then added `/path/to/X/bin` to the front of my PATH to be able to access the tool inside the X package. However, pip also created "python", "python3" etc links in `/path/to/X/bin` that linked to the `/usr/bin` counterparts. So when carla was starting, it located "python3" from `/path/to/X/bin` instead of `/usr/bin` because it was earlier in my PATH, and then proceeded to use the python venv environment for X instead of the operating system-installed python environment, and therefore could not find the PyQt5 module because it was not installed in the `/path/to/X`directory tree.

The solution was simply to move the `/path/to/X/bin` **after** `/usr/bin` in the PATH and thus carla no longer tries to use the wrong python program and works as expected.
