### ISSUE TITLE
Python Errors When Trying To Load In Windows OS

### ISSUE THREAD

**Issue by sound8** [falkTX/Carla#1562]
Windows 7 64Bit

A while back when trying to use version Carla 2.2 32Bit I was unable to run the application because I would instantly receive a Python error.  I then tried Carla 2.2 64Bit and the problem was solved no error upon opening.
I did not upgrade any versions after that until attempting recently.
I tried running both version 2.4.0 and 2.4.1 and now even when trying to run the 64Bit versions of these I am now getting similar error.

Traceback (most recent to call Last):
tons on python code errors show up here
OSError:[WinError87] The parameter is incorrect.

Does anyone else experience this error when trying to open Carla 2.4.1 for Windows?

**Comment by mxmilkiib** [comment]
I think you'll need to post more of a log than the final line to get any help.

If you put the log text between three `s, on the lines before and after, it will be easier to read.

**Comment by sound8** [comment]
Sorry about that, I have experienced this same issue with two different machines, same OS but different hardware, so I don't think that it is a hardware based issue.
This is why I didn't post the code because I thought that this might just be a common issue between Carla and Windows 7 that others would chime in with the same experience, but I guess not.

Here is the error code that pops up any time I try to run version 2.4.1
```
cx_Freeze: Phython error in main script

Traceback (most recent call last):
File ".\lib\__startup__.py", line 40, in run
File ".\lib\Console.py", line 37, in run
File "source\frontend\Carla", line 22, in <module>
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
File "<frozen zipimport>", line 259, in load_module
File ".\lib\carla_host.py", line 27, in <module>
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
File "<frozen zipimport>", line 259, in load_module
File ".\lib\ctypes\__init__.py", line 457, in <module>
File ".\lib\ctypes\__init__.py", line 373, in__init__
OSError: [WinError 87] The parameter is incorrect
```
If there are any other Windows 7 (64Bit) users, please share if you are able to use current version of Carla which at the moment is 2.4.1

Thank you for your response
