### ISSUE TITLE
Carla could not load 'modtools'

### ISSUE THREAD

**Issue by 0ka** [falkTX/Carla#1563]
Hi,

I'm using Carla on Ubuntu 20.04 installed via KXStudio
When I try to open the plugin GUI of the LV2 plugin https://github.com/stevie67/loopor I get the error that the module 'modtools' could not be found. How can I install this module?

```
Traceback (most recent call last):
  File "/usr/share/carla/carla_modgui.py", line 32, in <module>
    from modgui.host import HostWindow
  File "/usr/share/carla/modgui/host.py", line 34, in <module>
    from .webserver import WebServerThread, PORT
  File "/usr/share/carla/modgui/webserver.py", line 76, in <module>
    from modtools.utils import get_plugin_info, get_plugin_gui, get_plugin_gui_mini
ModuleNotFoundError: No module named 'modtools'

```
Thanks for your help.

**Comment by BlueMax** [comment]
Maybe its [this](https://pypi.org/project/modtools/) one. You can install it with 'pip' or other Python module installers.

**Comment by 0ka** [comment]
I already tried this module but it seems not to be the correct one. It is about pseudogenomes and has nothing to do with LV2 plugins.

**Comment by falkTX** [comment]
Just ignore it. the modgui support is quite experimental and doesnt work very well.
