### ISSUE TITLE
Windows VST QtGui import fail

### ISSUE THREAD

**Issue by kipieslim** [falkTX/Carla#1679]
As soon as i load Carla as a VST in a DAW i get the following error:

```
cx_Freeze: Python error in main script

---------------------------
Traceback (most recent call last):
  File ".\lib\__startup__.py", line 40, in run
  File ".\lib\Console.py", line 37, in run
  File "source\frontend\carla-plugin", line 22, in <module>
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
```

But both the stand-alone host and Carla-Control run without a problem.

OS: Windows 10 64-bit
Versions Affected: 2.4.2 and up 

I've got python 3.8.8 and Qt5 installed for safe measure, but that didn't fix the problem (maybe because it's supposed to be using the bundled libraries?)

**Comment by kipieslim** [comment]
This issue is resolved in version 2.5.1.
Thank you.
