### ISSUE TITLE
Runtime error - ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by BlueMax** [falkTX/Carla#1693]
bae7149 throws immediate runtime error.
Any idea what's wrong?
```
$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_app import (
  File "/usr/share/carla/carla_app.py", line 52, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
```

Arch Linux 5.19.13
AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=carla-git)

**Comment by Nefor111** [comment]
Same error then used as LMMS plugin.Can you help me to understand how it possible can be fixed?

**Comment by BlueMax** [comment]
It has been fixed in 2beb82b.
