### ISSUE TITLE
Carla not show GUI as plugin in LMMS

### ISSUE THREAD

**Issue by Nefor111** [falkTX/Carla#1696]
Arch Linux
Lmms 1.2.2
Carla-git AUR

Then trying open GUI in LMMS :

carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
File "/usr/share/carla/resources/carla-plugin", line 29, in
from carla_host import *
File "/usr/share/carla/resources/carla_host.py", line 53, in
import ui_carla_host
File "/usr/share/carla/resources/ui_carla_host.py", line 848, in
from widgets.racklistwidget import RackListWidget
File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in
from carla_skin import createPluginSlot
File "/usr/share/carla/resources/carla_skin.py", line 37, in
from carla_widgets import *
File "/usr/share/carla/resources/carla_widgets.py", line 96, in
from widgets.pixmapkeyboard import PixmapKeyboardHArea
File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in
from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
[carla] waitForClientFirstMessage() - read returned 0

After Installation utils module via pip3

[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
File "/usr/share/carla/resources/carla-plugin", line 29, in
from carla_host import *
File "/usr/share/carla/resources/carla_host.py", line 53, in
import ui_carla_host
File "/usr/share/carla/resources/ui_carla_host.py", line 848, in
from widgets.racklistwidget import RackListWidget
File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in
from carla_skin import createPluginSlot
File "/usr/share/carla/resources/carla_skin.py", line 37, in
from carla_widgets import *
File "/usr/share/carla/resources/carla_widgets.py", line 96, in
from widgets.pixmapkeyboard import PixmapKeyboardHArea
File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in
from utils import QSafeSettings
ImportError: cannot import name 'QSafeSettings' from 'utils' (/home/neff/.local/lib/python3.10/site-packages/utils/init.py)
[carla] waitForClientFirstMessage() - read returned 0

Standalone Carls version is working without any issue.

**Comment by falkTX** [comment]
This was fixed in https://github.com/falkTX/Carla/commit/2beb82b2e020068d41231364e2682253948e3f99
update your carla-git package

**Comment by Nefor111** [comment]
> This was fixed in [2beb82b](https://github.com/falkTX/Carla/commit/2beb82b2e020068d41231364e2682253948e3f99) update your carla-git package

Did it few times today.Not help.Carla itself works fime,carla as LMMS plugin not work.

**Comment by falkTX** [comment]
Ah I see now, this only happens with carla-plugin variants.
Should be fixed with b9df0854ed36c0cf21ebe6609490eb6c126e1dcd

**Comment by korincatnip** [comment]
I installed from the kxstudio repositories this morning (seemingly 2.6.0-alpha1) and am having what appears to be this same issue in Renoise:

```
[carla] Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 847, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_carla_resources_carla-plugin.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 847, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
[carla] waitForClientFirstMessage() - read returned 0

```
It seems the package carla-git isn't available, so is it just going to be a case of waiting a few days before the changes you've made above propagate into the repo? Not in any rush, obv, just wanted to check :)

Thank you for the work you do!

**Comment by falkTX** [comment]
hmm you are right, I pushed the wrong version to the repos, not your fault at all.
will correct this later today.

the carla-git version does work for now though.

**Comment by korincatnip** [comment]
Thank you so much for the speedy push, that's it fixed! Time to record some tunes. :)
