### ISSUE TITLE
Can't open plugin version on Ardour and MusE

### ISSUE THREAD

**Issue by minidcon7** [falkTX/Carla#1704]
Carla Version: 2.5.2
OS: Pop_OS 22.04

When I try load Carla like a LV2 or VST plugin don't load. 

Here the info about **Ardour 7** plugin scanner:

About LV2 :

```
URI: http://kxstudio.sf.net/carla/plugins/carlapatchbaycv
Bundle: file:///usr/lib/lv2/carla.lv2/
LV2 Category: 'Plugin'
Port 7 ('CV Input 1') has no known data type
Port 8 ('CV Input 2') has no known data type
Port 9 ('CV Input 3') has no known data type
Port 10 ('CV Input 4') has no known data type
Port 11 ('CV Input 5') has no known data type
Port 12 ('CV Output 1') has no known data type
Port 13 ('CV Output 2') has no known data type
Port 14 ('CV Output 3') has no known data type
Port 15 ('CV Output 4') has no known data type
Port 16 ('CV Output 5') has no known data type
```
About VST:

```
[Info]: Scanning: /usr/lib/carla/styles/carlastyle.so
[ERROR]: Missing entry method in VST2 plugin '/usr/lib/carla/styles/carlastyle.so'
[WARNING]: Cannot open VST2 module '/usr/lib/carla/styles/carlastyle.so'
Scan Failed.
```
In **MusE 4.1** I load Carla LV2 but don't shows GUI and I have the next output (I run MusE from terminal):

```
[carla] lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#idleInterface")
[carla] lv2ui_extension_data("http://yoshimi.sf.net/ns/lv2ext/programs#UIInterface")
[carla] lv2ui_extension_data("http://kxstudio.sf.net/ns/lv2ext/programs#UIInterface")
[carla] Trying to start carla-plugin using "/usr/lib/lv2/carla.lv2/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/lib/lv2/carla.lv2/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 847, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
```
And the info of VST version:

```
carla] waitForClientFirstMessage() - read returned 0
[carla] Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 53, in <module>
    import ui_carla_host
  File "/usr/share/carla/resources/ui_carla_host.py", line 847, in <module>
    from widgets.racklistwidget import RackListWidget
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 36, in <module>
    from carla_skin import createPluginSlot
  File "/usr/share/carla/resources/carla_skin.py", line 37, in <module>
    from carla_widgets import *
  File "/usr/share/carla/resources/carla_widgets.py", line 96, in <module>
    from widgets.pixmapkeyboard import PixmapKeyboardHArea
  File "/usr/share/carla/resources/widgets/pixmapkeyboard.py", line 29, in <module>
    from utils import QSafeSettings
ModuleNotFoundError: No module named 'utils'
```

**Comment by arnwas** [comment]
Can confirm for 2.5.4 in ardour 7.4
