### ISSUE TITLE
Carla refuses to work as a plugin at all on Debian 11

### ISSUE THREAD

**Issue by kamkamkamkamkamkamkamkam** [falkTX/Carla#1714]
When I try to load Carla as a VST in REAPER I get this output and a blank plugin
`jack: created client
jack: non-realtime threads
jack: activated client
/dev/cpu_dma_latency: permission denied
[carla] Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 58, in <module>
    from carla_frontend import CarlaFrontendLib
ModuleNotFoundError: No module named 'carla_frontend'
[carla] waitForClientFirstMessage() - read returned 0
`
And when I try to use the version embedded in LMMS, I get the exact same error
`[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 58, in <module>
    from carla_frontend import CarlaFrontendLib
ModuleNotFoundError: No module named 'carla_frontend'
[carla] waitForClientFirstMessage() - read returned 0
[carla] Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla-plugin", line 29, in <module>
    from carla_host import *
  File "/usr/share/carla/resources/carla_host.py", line 58, in <module>
    from carla_frontend import CarlaFrontendLib
ModuleNotFoundError: No module named 'carla_frontend'
[carla] waitForClientFirstMessage() - read returned 0
`
I know other people who use Debian with this problem as well and it's really frustrating.

**Comment by kamkamkamkamkamkamkamkam** [comment]
Also I should point out I was using the version from the KXStudio repositories, but when I switched to the other version hosted there it started working (though this wasn't the case before when I tried both).
