### ISSUE TITLE
Cannot start carla from command line ubuntu 24.04. ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by stevekanger** [falkTX/Carla#1903]
I can no longer start carla from the command line using the `carla` command. I get the following error.

```
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 40, in <module>
    from PyQt5.QtCore import (
ModuleNotFoundError: No module named 'PyQt5'
``` 

PyQt5 is installed on my system via apt. Here is the result of doing `sudo apt install python3-pyqt5`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pyqt5 is already the newest version (5.15.10+dfsg-1build6).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
```

Not sure what to do here. I have a script the I use to launch Qjackctl, Carla and OBS. This no longer works. I can however open carla via app launcher. So not sure what has changed recently to where carla doesn't lauch via command line anymore. This has to be a recent thing because I have used the `carla` command before on ubuntu 24.04 and it worked. It should be noted that I am on sway but have tried in ubuntu Gnome as well with the same result. I have also tried different terminal emulators (Foot and gnome-terminal) and also with zsh and bash. This problem seems to have happened within the last month or so. I have tried uninstalling and purging carla and then reinstalling but I get the same result.

**Comment by stevekanger** [comment]
Turns out there was an issue with a conflicting version of python installed by brew so it was not related to this codebase.
