### ISSUE TITLE
Carla Hangs on Startup (undefined symbol: carla_nsm_init)

### ISSUE THREAD

**Issue by ssj71** [falkTX/Carla#213]
I just updated this other machine that I hadn't used for a while tonight and now can't start carla. Not sure if it would've worked before updating. Xubuntu 14.04 with kxstudio ppas. Carla-git is the package.

When I run it in the terminal I get:
```
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 14: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-ttf-sil-andika.conf", line 32: Having multiple <family> in <alias> isn't supported and may not work as expected
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.0
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 69, in <module>
    host = initHost(initName, libPrefix, False, False, True)
  File "/usr/share/carla/carla_host.py", line 2147, in initHost
    host = PluginClass() if isPlugin else CarlaHostQtDLL(os.path.join(pathBinaries, libname))
  File "/usr/share/carla/carla_backend_qt.py", line 104, in __init__
    CarlaHostDLL.__init__(self, libName)
  File "/usr/share/carla/carla_backend.py", line 2351, in __init__
    self.lib.carla_nsm_init.argtypes = [c_int, c_char_p]
  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/carla/libcarla_standalone2.so: undefined symbol: carla_nsm_init
```
It just hangs there. Anyway, hopefully I'm not bogging you down with some weird setup issues I might have, but I figured false bug reports are better than some unknown real issue lurking. 

EDIT: I just confirmed that the issue does NOT occur on my other machine with similar setup (ubuntu 14.04 kx ppas).

**Comment by falkTX** [comment]
Make sure you got all the updates, and then try a reinstall:
```
sudo apt-get install carla-git carla-data --reinstall
```

**Comment by ssj71** [comment]
Ya I had several broken python packages for some reason. Once I worked through them it worked. Thanks! (And sorry for the noise)
