### ISSUE TITLE
Errors when loading Dexed in Carla

### ISSUE THREAD

**Issue by Penguinum** [falkTX/Carla#216]
Not sure, maybe this is a problem in Dexed, but before the last Carla's update (or one of last updates) it worked.
When trying to load Dexed (LV2 version, VST version is not shown in "add plugin" dialog for some reason) I'm getting this output:
```
Carla assertion failure: "fLatencyIndex == static_cast<int32_t>(j)" in file CarlaPluginLV2.cpp, line 2201
Parameter 'Cutoff' too high! - 56432976199680.000000/1.000000
Parameter 'Resonance' too high! - 899534028800.000000/1.000000
Parameter 'Output' too high! - 15448396456910745814171648.000000/1.000000
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla_host.py", line 838, in slot_handlePluginAddedCallback
    pitem = self.ui.listWidget.createItem(pluginId, self.fSavedSettings[CARLA_KEY_MAIN_USE_CUSTOM_SKINS])
  File "/usr/share/carla/resources/racklistwidget.py", line 219, in createItem
    return RackListItem(self, pluginId, useSkins)
  File "/usr/share/carla/resources/racklistwidget.py", line 82, in __init__
    self.recreateWidget(firstInit = True)
  File "/usr/share/carla/resources/racklistwidget.py", line 159, in recreateWidget
    self.fWidget = createPluginSlot(self.fParent, self.host, self.fPluginId, self.fOptions)
  File "/usr/share/carla/resources/carla_skin.py", line 1780, in createPluginSlot
    return PluginSlot_Presets(parent, host, pluginId, skinStyle)
  File "/usr/share/carla/resources/carla_skin.py", line 1543, in __init__
    self.ready()
  File "/usr/share/carla/resources/carla_skin.py", line 598, in ready
    paramWidget.setValue(self.host.get_internal_parameter_value(self.fPluginId, paramIndex))
  File "/usr/share/carla/resources/pixmapdial.py", line 237, in setValue
    QDial.setValue(self, int(normValue * 10000))
TypeError: QAbstractSlider.setValue(int): argument 2 has unexpected type 'int'
sorry, can't map this plugin to canvas client 0 0
Traceback (most recent call last):
  File "/usr/share/carla/resources/pixmapdial.py", line 402, in paintEvent
    painter.drawArc(4.0, 4.0, 26.0, 26.0, startAngle, spanAngle)
TypeError: arguments did not match any overloaded call:
  QPainter.drawArc(QRectF, int, int): argument 1 has unexpected type 'float'
  QPainter.drawArc(QRect, int, int): argument 1 has unexpected type 'float'
  QPainter.drawArc(int, int, int, int, int, int): argument 6 has unexpected type 'float'
QPainter::end: Painter ended with 2 saved states
```
And rack tab (when instrument is shown on rack, sometimes it is not shown) looks like this: ![Image](http://storage3.static.itmages.com/i/15/0301/h_1425220269_3429868_545ebc1408.png)
Carla's version: 1.9.6 from KXStudio.

**Comment by SpotlightKid** [comment]
I can't confirm this with Dexed 0.6.1 (LV2) and Carla (Standalone Patchbany mode) built from Git as of today. VST version of Dexed also works.

**Comment by Penguinum** [comment]
The strange thing is that after removing all Carla's config files (~/.config/falkTX/Carla*) Dexed loads without problems, but only for the first time. Next time I launch Carla the problem appears again.

**Comment by falkTX** [comment]
this is a bug in dexed, some of its parameters are not initializes properly, leading to weird values.

to be fixed soon

**Comment by falkTX** [comment]
This is now been fixed in https://github.com/DISTRHO/DISTRHO-Ports/commit/05bd41f95b7851cf719b4fc6c362d0340229a8ea

I've updated the kxstudio repos, please test.

**Comment by Penguinum** [comment]
Everything works now. (Thank you!)

**Comment by falkTX** [comment]
Thanks for the testing, closing bug report now.
