### ISSUE TITLE
carla_database.py problem and list of plugins

### ISSUE THREAD

**Issue by lekimtek** [falkTX/Carla#300]
carla_database.py problem and list of plugins

When I install carlavst in linux64bits I can not see the list of plugins and gives me this error:

Traceback (most recent call last):
  File "/usr/share/carla/carla_host.py", line 725, in slot_pluginAdd
    dialog = PluginDatabaseW(self.fParentOrSelf, self.host)
  File "/usr/share/carla/carla_database.py", line 1193, in __init__
    self._reAddPlugins()
  File "/usr/share/carla/carla_database.py", line 1612, in _reAddPlugins
    self._addPluginToTable(plugin, "VST2")
  File "/usr/share/carla/carla_database.py", line 1395, in _addPluginToTable
    if plugin['API'] != PLUGIN_QUERY_API_VERSION and ptype == self.tr("Internal"):
TypeError: string indices must be integers

Helpme please

**Comment by falkTX** [comment]
you probably updated from an old version of carla.
if you delete ~/.config/falkTX/Carla* files carla will start again.

**Comment by lekimtek** [comment]
Ok thank you very much has been fixed.
Like you said I have deleted the ~/.config/falkTX/Carla* directory and everything has been solved.

Thank you!

**Comment by falkTX** [comment]
Forgot to close this bug.
