### ISSUE TITLE
PyQt v5.6 compatibility

### ISSUE THREAD

**Issue by pchome** [falkTX/Carla#400]
> In previous versions if a signal was connected to a method that was decorated by pyqtSlot(), and the signatures of the signal and slot were incompatible, then the connection was made anyway as if the method had not been decorated. This behaviour was a bug and not a feature.

http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html

possible fix (?):
```
diff --git a/source/carla_host.py b/source/carla_host.py
index efa6632..1281ac5 100644
--- a/source/carla_host.py
+++ b/source/carla_host.py
@@ -670,7 +670,7 @@ class HostWindow(QMainWindow):
     # --------------------------------------------------------------------------------------------------------
     # Engine (host callbacks)
 
-    @pyqtSlot(str)
+    @pyqtSlot(int, int, str)
     def slot_handleEngineStartedCallback(self, processMode, transportMode, driverName):
         self.ui.menu_PluginMacros.setEnabled(True)
         self.ui.menu_Canvas.setEnabled(True)
diff --git a/source/carla_panels.py b/source/carla_panels.py
index 9cf36a5..eebc76d 100644
--- a/source/carla_panels.py
+++ b/source/carla_panels.py
@@ -222,7 +222,7 @@ class CarlaPanelTime(QDialog):
     # --------------------------------------------------------------------------------------------------------
     # Engine callbacks
 
-    @pyqtSlot(str)
+    @pyqtSlot(int, int, str)
     def slot_handleEngineStartedCallback(self, processMode, transportMode, driverName):
         self.fSampleRate = self.host.get_sample_rate()
         self.refreshTransport(True)
```

current master output:
```
$ carla
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.3
  Qt version:     5.6.0
  PyQt version:   5.6.1.dev1604271126
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 52, in <module>
    gui = HostWindow(host, True)
  File "/usr/share/carla/carla_host.py", line 256, in __init__
    self.ui.panelTime = CarlaPanelTime(host, self)
  File "/usr/share/carla/carla_panels.py", line 90, in __init__
    host.EngineStartedCallback.connect(self.slot_handleEngineStartedCallback)
TypeError: decorated slot has no signature compatible with CarlaHostSignals.EngineStartedCallback[int, int, str]
```

**Comment by falkTX** [comment]
That is nice, didn't know pyqt did that now.
Sadly I don't have PyQt5.6 here for testing.
Are those the only errors that appear? If you add a plugin, open settings and do other actions do ant other errors/warnings appear?

PS: This is a good candidate for a pull request ;)

**Comment by pchome** [comment]
With this patch I can launch Carla, configure and connect Guitarix.
I have newly installed Carla and some dependencies, so no other tests was done.
But yes, there are errors when I try to add plugins:
```
Traceback (most recent call last):
  File "/usr/share/carla/carla_host.py", line 970, in slot_handlePluginAddedCallback
    pitem = self.ui.listWidget.createItem(pluginId, self.fSavedSettings[CARLA_KEY_MAIN_USE_CUSTOM_SKINS])
  File "/usr/share/carla/racklistwidget.py", line 229, in createItem
    return RackListItem(self, pluginId, useSkins)
  File "/usr/share/carla/racklistwidget.py", line 82, in __init__
    self.recreateWidget(firstInit = True)
  File "/usr/share/carla/racklistwidget.py", line 169, in recreateWidget
    self.fWidget = createPluginSlot(self.fParent, self.host, self.fPluginId, self.fOptions)
  File "/usr/share/carla/carla_skin.py", line 1859, in createPluginSlot
    return PluginSlot_Default(parent, host, pluginId, skinStyle)
  File "/usr/share/carla/carla_skin.py", line 1503, in __init__
    AbstractPluginSlot.__init__(self, parent, host, pluginId, skinStyle)
  File "/usr/share/carla/carla_skin.py", line 274, in __init__
    self.fEditDialog = PluginEdit(self, host, self.fPluginId)
  File "/usr/share/carla/carla_widgets.py", line 555, in __init__
    self.ui.dial_drywet.realValueChanged.connect(self.slot_dryWetChanged)
TypeError: decorated slot has no signature compatible with PixmapDial.realValueChanged[float]
``` 

Unfortunately I not so familiar with Python, and I'm not sure my fix is correct.
But ok: #401

**Comment by falkTX** [comment]
merged. if more of those happen let me know.
thanks
