### ISSUE TITLE
TyrellN6 crashes Carla

### ISSUE THREAD

**Issue by progwolff** [falkTX/Carla#440]
In the latest git version of Carla, loading TyrellN6 (native linux 64, http://www.amazona.de/wp-content/tyrell/TyrellN6_V303_Linux.tar.gz) leads to a segfault: 

```
...

CarlaEngine::callback(29:ENGINE_CALLBACK_ENGINE_STARTED, 0, 3, 1, 0,000000, "JACK")
carla_get_sample_rate()
[New Thread 0x7fffc6ffd700 (LWP 29238)]
[New Thread 0x7fffc67fc700 (LWP 29239)]
[New Thread 0x7fffc517f700 (LWP 29241)]

Thread 7 "carla-patchbay" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd4084700 (LWP 29236)]
0x00007fffdaf6c7e6 in ?? () from /usr/lib/carla/libcarla_standalone2.so
(gdb) backtrace
#0  0x00007fffdaf6c7e6 in  () at /usr/lib/carla/libcarla_standalone2.so
#1  0x00007fffdaf6cd1d in  () at /usr/lib/carla/libcarla_standalone2.so
#2  0x00007fffdaf29d24 in  () at /usr/lib/carla/libcarla_standalone2.so
#3  0x00007fffdaf0a81b in  () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007fffdaf08e8a in void juce::AudioProcessorGraph::processAudio<float>(juce::AudioBuffer<float>&, juce::MidiBuffer&) () at /usr/lib/carla/libcarla_standalone2.so
#5  0x00007fffdaf28822 in CarlaBackend::PatchbayGraph::process(CarlaBackend::CarlaEngine::ProtectedData*, float const* const*, float* const*, int) () at /usr/lib/carla/libcarla_standalone2.so
#6  0x00007fffdaf3f291 in  () at /usr/lib/carla/libcarla_standalone2.so
#7  0x00007fffdaf3f5bf in  () at /usr/lib/carla/libcarla_standalone2.so
#8  0x00007fffd935e26e in  () at /usr/lib/libjack.so.0
#9  0x00007fffd935da38 in  () at /usr/lib/libjack.so.0
#10 0x00007fffd9375290 in  () at /usr/lib/libjack.so.0
#11 0x00007ffff76f6454 in start_thread () at /usr/lib/libpthread.so.0
#12 0x00007ffff74397df in clone () at /usr/lib/libc.so.6

...
```

The same vst could be used without problems before https://github.com/falkTX/Carla/commit/d1423a10c37d75294a9e7de7a36e5264eaae8e0c

**Comment by falkTX** [comment]
I'm surprised that you can even load u-he plugins.

Please try with the latest git again, did an ugly hack that allows to load u-he stuff on carla standalone.

**Comment by progwolff** [comment]
Great, may thanks once again!

Just out of interest: what's wrong with u-he?

**Comment by falkTX** [comment]
I'd love to know...
Seems to be a symbol conflict with u-he plugins and libcarla_standalone2.so.
Hopefully the change I did doesn't break anything.
