### ISSUE TITLE
Cannot import PyQt5.QtCore.pyqtWrapperType

### ISSUE THREAD

**Issue by lithm** [falkTX/Carla#458]
This prevents Carla from launching on Arch Linux with PyQt5 5.7.1.

```
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 40, in <module>
    import ui_carla_host
  File "/usr/share/carla/ui_carla_host.py", line 507, in <module>
    from racklistwidget import RackListWidget
  File "/usr/share/carla/racklistwidget.py", line 38, in <module>
    from carla_skin import *
  File "/usr/share/carla/carla_skin.py", line 44, in <module>
    from carla_widgets import *
  File "/usr/share/carla/carla_widgets.py", line 28, in <module>
    from PyQt5.QtCore import pyqtSignal, pyqtSlot, pyqtWrapperType, Qt, QByteArray, QSettings, QTimer
ImportError: cannot import name 'pyqtWrapperType'
```

Of the two modules that import `pyqtWrapperType`, `carla_widgets` does not use it at all, and `carla_backend_qt` only uses it for the dead `PyQtMetaClass`, so why not remove both that class and these imports?

**Comment by falkTX** [comment]
Fixed in 8aa4efc58ddc9641376048b55fc7097b45986792.

The hotfix-1.9.7 branch is there if you don't want new experimental stuff.
