### ISSUE TITLE
Unable to open Carla after a system upgrade

### ISSUE THREAD

**Issue by io7m** [falkTX/Carla#561]
Hello.

I'm using Arch Linux. I updated this morning and now on trying to open Carla, I see the following:

```
$ carla
Using "fusion" theme
Carla 1.9.7 (2.0-beta5) started, status:
  Python version: 3.6.3
  Qt version:     5.10.0
  PyQt version:   5.9.2
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 46, in <module>
    host = initHost(initName, libPrefix, False, False, True)
  File "/usr/share/carla/carla_host.py", line 2233, in initHost
    host = HostClass() if HostClass is not None else CarlaHostQtDLL(os.path.join(pathBinaries, libname))
  File "/usr/share/carla/carla_backend_qt.py", line 96, in __init__
    CarlaHostDLL.__init__(self, libName)
  File "/usr/share/carla/carla_backend.py", line 2106, in __init__
    self.lib = CDLL(libName, RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: liblinuxsampler.so.4: cannot open shared object file: No such file or directory
```

I'm assuming what's happening here is that there's a stale `.so` somewhere in my system that still links to `liblinuxsampler.so.4`. `liblinuxsampler.so.4` no longer exists (although I do have a `liblinuxsampler.so.5`). I've cleared `/etc/ld.so.cache`.

Is there some way to get Carla to tell me which library is causing this problem?

**Comment by io7m** [comment]
Apologies for the noise; it was Carla itself that needed re-linking. A rebuild got rid of the issue.
