### ISSUE TITLE
Can not run Carla on Ubuntu 18.04

### ISSUE THREAD

**Issue by Sir-hennihau** [falkTX/Carla#629]
Hey,
I tried to build Carla from source. I run on Ubuntu 18.04.

Here is my `$ make features`:

```
---> Main features 
Front-End:     YES (Using Qt4)
LV2 plugin:    YES
VST plugin:    YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  NO  [Missing PulseAudio]
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST:      YES (with UI)

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      YES (bridge)
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
GIG: NO    [LinuxSampler missing or too old]
SF2: NO    [FluidSynth missing]
SFZ: NO    [LinuxSampler missing or too old]

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO
```

Dev dependencies seem to be met.

Installation runs without errors.

**Running Carla throws, though:**

```
$ carla

Traceback (most recent call last):
  File "/usr/local/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/local/share/carla/carla_host.py", line 34, in <module>
    from PyQt4.QtCore import qCritical, QFileInfo, QModelIndex, QPointF, QTimer
ModuleNotFoundError: No module named 'PyQt4'

```

No interface oder process launches. Someone knows what's missing?

**Comment by falkTX** [comment]
is that all it throws? nothing else?
did you try to run it directly from code? ie, using `./source/carla`

**Comment by SpotlightKid** [comment]
There must be some lines missing from the Python exception message.

**Comment by Sir-hennihau** [comment]
@falkTX Yeah, that is all it throws. Trying to run it directly from code results in the same error.

@SpotlightKid Yeah, you are right. I actually failed to properly copy paste. Sorry for that. I'll edit my post, too.

```
Traceback (most recent call last):
  File "/usr/local/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/local/share/carla/carla_host.py", line 34, in <module>
    from PyQt4.QtCore import qCritical, QFileInfo, QModelIndex, QPointF, QTimer
ModuleNotFoundError: No module named 'PyQt4'

```
I am a little confused since make features displays that Qt4 seems to be okay.

**Comment by Sir-hennihau** [comment]
@SpotlightKid 

The first line of `/usr/local/share/carla/carla`
is
`from carla_host import *`


The full file is

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Carla plugin host
# Copyright (C) 2011-2017 Filipe Coelho <falktx@falktx.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# For a full copy of the GNU General Public License see the doc/GPL.txt file.

# ----------------------------------------------------------------------------------------------------------------------
# Imports (Custom Stuff)

from carla_host import *

# ----------------------------------------------------------------------------------------------------------------------
# Main

if __name__ == '__main__':
    # ------------------------------------------------------------------------------------------------------------------
    # Read CLI args

    initName, libPrefix = handleInitialCommandLineArguments(__file__ if "__file__" in dir() else None)

    # ------------------------------------------------------------------------------------------------------------------
    # App initialization

    app = CarlaApplication("Carla2", libPrefix)

    # ------------------------------------------------------------------------------------------------------------------
    # Set-up custom signal handling

    setUpSignals()

    # ------------------------------------------------------------------------------------------------------------------
    # Init host backend

    host = initHost(initName, libPrefix, False, False, True)
    loadHostSettings(host)

    # ------------------------------------------------------------------------------------------------------------------
    # Create GUI

    gui = HostWindow(host, True)

    # ------------------------------------------------------------------------------------------------------------------
    # Show GUI

    gui.show()

    # ------------------------------------------------------------------------------------------------------------------
    # App-Loop

    app.exit_exec()
```

**Comment by Sir-hennihau** [comment]
@SpotlightKid Yeah, that was the right hint.

My result was
```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4.QtGui import QWidget
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt4'
```

After a quick Google search I ended up installing `sudo apt-get install python3-pyqt4` and now the Carla interface loads properly.

Thanks for your help and an even bigger thanks @SpotlightKid and @falkTX for making all this software and support. You guys are amazing!
