### ISSUE TITLE
ReaEQ plugin not working

### ISSUE THREAD

**Issue by shw** [falkTX/Carla#922]
I downloaded ReaPlugs to use with Carla. Every one I tried seems to work ok, but the ReaEQ one won't even show up on the patchbay when I add it.

Is there a way I can debug it? Some kind of log or a console I can check to provide more information?

**Comment by falkTX** [comment]
You can run `/usr/lib/carla/carla-discovery-native` against the binary to see why it is not being listed.

**Comment by falkTX** [comment]
I might have misunderstood the question, the plugin is detected, but does not appear in patchbay when added? are you using the windows version of the plugins, or the native linux versions?

**Comment by shw** [comment]
Yes - the second one. It's listed and just does not appear when I'm trying to add it.
I don't see Linux version of those plugins.
I tried Windows 64-bit versions. 32-bit do not appear in list of plugins even if I remove the 64-bit ones and refresh.

I forgot to say that I'm running Windows version of Carla.

**Comment by shw** [comment]
Downloaded 32-bit version of Carla and 32-bit version of all those plugins seems to work. So there's only a problem with 64-bit version of either the plugins or Carla.

**Comment by KFlab** [comment]
I have same problem , and I try to run Carla.exe in Debug floder
Carla 2.0.0 started, status:
  Python version: 3.4.4
  Qt version:     5.5.1
  PyQt version:   5.5.1
  Binary dir:     C:\Tool\Carla_2.0.0-win64\Carla
  Resources dir:  C:\Tool\Carla_2.0.0-win64\Carla\resources

MidiInWinMM::initialize: no MIDI input devices currently available.
shows that 

Traceback (most recent call last):
  File "Z:\home\falktx\Personal\FOSS\GIT\falkTX\Carla\source\frontend\carla_host.py", line 1069, in slot_pluginAdd
  File "Z:\home\falktx\Personal\FOSS\GIT\falkTX\Carla\source\frontend\carla_backend.py", line 2549, in add_plugin
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
