### ISSUE TITLE
Refresh function is broken: AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by yurivict** [falkTX/Carla#971]
I am trying 2.1-b1-test1-111-gccb0b4bb. The "Refresh" function prints this into the log and doesn't discover newly-installed plugins:

```
AttributeError: 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "/usr/local/share/carla/carla_database.py", line 1545, in slot_checkPlugin
    self.TABLEWIDGET_ITEM_NAME).data(Qt.UserRole+1)
AttributeError: 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "/usr/local/share/carla/carla_database.py", line 1545, in slot_checkPlugin
    self.TABLEWIDGET_ITEM_NAME).data(Qt.UserRole+1)
```

**Comment by falkTX** [comment]
Should be fixed now, please try again (update and reinstall)

**Comment by falkTX** [comment]
Assumed fixed, otherwise please reopen
