### ISSUE TITLE
arm not starting properly

### ISSUE THREAD

**Issue by dev-procedural** [falkTX/Carla#977]
Hi there,

   First of all thanks a lot for this , it is awesome and have made my days full of joy xD. I'm running a C.H.I.P. arm,  compiled as mentioned in the guide but when starting get the below error, would it be please possible some help ? 

OS SPECS:
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
  BUILD_ID=Fri Dec  9 22:09:06 UTC 2016
  VARIANT="Debian on C.H.I.P"
  VARIANT_ID=SERVER

```

```
Carla 2.0.90 (2.1-alpha2) started, status:
  Python version: 3.4.2
  Qt version:     5.3.2
  PyQt version:   5.3.2
  Binary dir:     /usr/local/lib/carla
  Resources dir:  /usr/local/share/carla/resources
Could not resolve property : linearGradient5167
Could not resolve property : linearGradient5167
Could not resolve property : pattern5614
Could not resolve property : pattern5626
Could not resolve property : radialGradient3709
Could not resolve property : linearGradient3893-1
Could not resolve property : linearGradient3893-1
Could not resolve property : linearGradient3893-1
Traceback (most recent call last):
  File "/usr/local/share/carla/carla", line 52, in <module>
    gui = HostWindow(host, True)
  File "/usr/local/share/carla/carla_host.py", line 404, in __init__
    self.loadSettings(True)
  File "/usr/local/share/carla/carla_host.py", line 1772, in loadSettings
    self.fFavoritePlugins = settingsDBf.value("PluginDatabase/Favorites", [], type=list)
```

**Comment by fhennig** [comment]
Did you install all the dependencies?

    sudo apt install python3-pyqt5.qtsvg python3-rdflib pyqt5-dev-tools \
      libmagic-dev liblo-dev libasound2-dev libpulse-dev libx11-dev \
      libgtk2.0-dev libgtk-3-dev libqt4-dev qtbase5-dev libfluidsynth-dev

**Comment by falkTX** [comment]
This is fixed in latest git, by ensuring saved data types match what the application expects.
